### ISSUE TITLE
BIDS directory

### ISSUE THREAD

**Issue by FredericBr** [nwd2918/MRS-voxel-plot#4]
Hi @nwd2918 and @thvuongtmu ,

First of all, I want to thank you for your great script.
Second, it is just a suggestion, but according to the BIDS structure, the directory is:
Participant > session > data-types > (i.e. sub-01 > ses-01 > mrs >), although your soft just works with this structure "Participant > data-types ", it could be great if your soft can follow this structure!

Moreover, the name of the mask (for you: mrs-voxel_mni-space.nii.gz) is often personalized in BIDS (sub-01-mrs-voxel_mni-space.nii.gz), your script would be enhanced if it could use a more flexible name of it.

Best,
Frederic

**Comment by nwd2918** [comment]
Glad to hear you're finding the script useful.

The session level is optional in the BIDS standard but you're right that it would be important to have the flexibility to include it. Similarly, making the filenames individualised is also a good idea. The plan is to do a general overhaul of the code so these are things that we will definitely include.

Thanks for the good suggestions.
